version: '3.1'

services:
  # The frontend of the game.
  app:
    image: node:10.16.0
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./elm.json:/app/elm.json
      - ./package.json:/app/package.json
    ports:
      - 1234:1234
      - 1235:1235
    command: [ "npm", "run", "docker" ]
